#!/usr/bin/env bash
# A Bash script that loops on line 4 bad luck and on line 8 good luck the rest is best school

count=0

while [ $count -lt 10 ]
do
	if [ $count -eq 3 ]
		then
			echo "bad luck"
	elif [ $count -eq 7 ]
		then
			echo "good luck"
	else
		echo "Best School"
	fi
	count=$((count+1))
done